### ISSUE TITLE
Dinga Dinga Dinga

### ISSUE THREAD

**Issue by anamikoye** [Burugux/suca-africa#1]
Haeee.. comments. Good job.. Only problem, make the slideshow full length. To fill up the whole screen.. 

Also, don't need an about page. Need a gallery page.. and Find Us.
Then I think the menu would be better served within the header, no?

**Comment by Burugux** [comment]
* I'll try to make the carousel full page but it may affect the tabs I have on it. Regardless lemme try and see how I can move things around.
* I can add a gallery page...should it have all the photos you guys took?
* About the find us page... I'm thinking of embedding google maps with a marker to the property. What do you think?

**Comment by Burugux** [comment]
1.

**Comment by anamikoye** [comment]
You were right, it has affected the tabs. Could you make it so that they pop up? Are visible right at the bottom.
